### ISSUE TITLE
Game crashes at startup (1.16.5)

### ISSUE THREAD

**Issue by mrthethatone** [polgaria/FarLands#94]
So i downloaded the mod, put it in my mods folder, and then tried to launch the game, But the game crashes.
Here is the massive chunk of text and shit that was in the game output. (i dont know were logs save)

**Mixin apply failed farlands.mixins.json:common.entity.EntityMixin -> net.minecraft.class_1297: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyConstant annotation on clampTeleportToNegativeDoubleMaxValueXZ could not find any targets matching 'Lnet/minecraft/class_1297;method_5731(Lnet/minecraft/class_2874;)Lnet/minecraft/class_1297;' in net.minecraft.class_1297. Using refmap FarLands-refmap.json [PREINJECT Applicator Phase -> farlands.mixins.json:common.entity.EntityMixin -> Prepare Injections ->  -> constant$zpn000$clampTeleportToNegativeDoubleMaxValueXZ(D)D -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyConstant annotation on clampTeleportToNegativeDoubleMaxValueXZ could not find any targets matching 'Lnet/minecraft/class_1297;method_5731(Lnet/minecraft/class_2874;)Lnet/minecraft/class_1297;' in net.minecraft.class_1297. Using refmap FarLands-refmap.json [PREINJECT Applicator Phase -> farlands.mixins.json:common.entity.EntityMixin -> Prepare Injections ->  -> constant$zpn000$clampTeleportToNegativeDoubleMaxValueXZ(D)D -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275)
	at org.spongepowered.asm.mixin.injection.struct.ModifyConstantInjectionInfo.<init>(ModifyConstantInjectionInfo.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:211)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:425)
	at net.minecraft.client.main.Main.main(Main.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)**

How do i fix this?

**Comment by PercyDan54** [comment]
This mod does not support 1.16 yet
